### ISSUE TITLE
Complete native driver

### ISSUE THREAD

**Issue by abeaumont** [bblfsh/cpp-driver#2]

**Comment by Timus1712** [comment]
Hello!

I'm doing my Master thesis and it's related to analyze some properties of source codes using Machine Learning. Of course, products of your company is very interesting for me and thank you for open sourcing them!

But cpp-driver is very important for me. Do you have any ETA for this? Or at least what is priority of this effort? There were no updates in this repo for a long time...

IIUC, right now this driver supports building AST, but not UAST. Is this correct?

Thanks in advance for your answers!

**Comment by juanjux** [comment]
Hi, thank for your interest, we're always happy to be useful to more users!

The cpp driver is definitely a priority, but we currently have a higher one working with a new version of the drivers SDK and the UAST format that will be much more useful to users. 

The current driver produced the native AST at some point (using IBM's CDT in case you want to take a look) but it's probably outdated. The reason why the development on it paused its because C++ is a hard beast to tame because of the preprocessor and we didn't take the easy way of expanding it but instead parse it with nodes representing its statements and macros, but as you can imagine the preprocessor branches can change the shape of the AST inside them, so we need to find a way to handle that.

**Comment by smola** [comment]
see https://github.com/bblfsh/cpp-driver/pull/5

**Comment by creachadair** [comment]
Ping @juanjux. This looks to be finished—is there anything further to be done on this issue?

**Comment by juanjux** [comment]
The change from RC to final 1.0 version would involve me testing it with a lot of real world code. Hope to do it this week.
