### ISSUE TITLE
Stream output instead of buffering to memory

### ISSUE THREAD

**Issue by dennwc** [bblfsh/cpp-driver#22]
It seems like the driver currently buffers the serialized JSON into memory instead of streaming it:

https://github.com/bblfsh/cpp-driver/blob/e7a25c8d21fee6d7f2ce701c6c11b01868ecd422/native/src/main/java/tech/sourced/babelfish/Main.java#L41

This causes OOM kills when processing large files.

@juanjux Is there any reason to not use `Sytem.out` here directly?

**Comment by juanjux** [comment]
As usually happens with Java, things are somewhat convoluted. We use Jackson for the json generation. Jackson's [jsonFactory.createGenerator](https://fasterxml.github.io/jackson-core/javadoc/2.2.0/com/fasterxml/jackson/core/JsonFactory.html#createGenerator(java.io.File,%20com.fasterxml.jackson.core.JsonEncoding)) method require and `OutputStream` class. 

But its probably true that `ByteArrayOutputStream` is not the best option, I'll try with the other subclasses.

**Comment by juanjux** [comment]
Ok, I managed to find a way to use `System.out` :+1: 

Now the problem dissapears, at least on the Java part. The file in #19 still uses a lot of memory, more than my system has (16GB) if I let it run forever (causing the kernel OOM killer to nuke it at the end), but the memory usage has moved from the Java process to the `driver` one (so it seems at some points drivers or the SDK is keeping everything in memory too).

But since this issue is about the stream output I'll close it once the PR I'll publish soon is merged.
