### ISSUE TITLE
Comments disappearing in beginning of file

### ISSUE THREAD

**Issue by r0mainK** [bblfsh/cpp-driver#60]
Hey ! While working on `uast2clickhouse` I noticed that, if you take a file with this structure:

```
// comment 1
#pragma once
// comment 2
#include <unordered_map>
// comment 3
#include <SFML/Graphics.hpp>
// comment 4
namespace gui
// comment 5
{
class sfml2_font : public font_i
{
public:
    sfml2_font(const sf::Font& font);
};
}
```

Then the comments 1 through 4 do not appear in the UAST. For example, for [this file](https://github.com/Nocte-/hexahedra/blob/master/hexa/client/gui/sfml2.hpp) from which I based my example, the licensing block at the beginning completely disappears. Was wondering if this was expected behavior, or indeed a bug?

**Comment by kuba--** [comment]
Let me mark it as a bug, right now.
If I parse it with native CDT parser I can see comments 4, 5 as a `LeadingComments` in native AST. But all comments above _preprocesor directives_ exists as a part of `IASTClass` Snippet:
```
    "IASTClass": "CPPASTTranslationUnit",
    "Snippet": "// comment 1  #pragm...",
```

It can be a bug in CDT. I'll take a look.

**Comment by kuba--** [comment]
Shorter test case to reproduce it:
```c++
// comment1
#pragma once
// comment2
class C
{
};
```

**Comment by kuba--** [comment]
It looks like a yet another problem in CDT (because comments are also missed in native AST). The preprocessor statements' comments can be fixed (kind of) by adding `serializePreprocStatements(node);`
here: https://github.com/bblfsh/cpp-driver/blob/dfc7c134de12f5ecd79227f122e2c03c3cf95f15/native/src/main/java/tech/sourced/babelfish/JsonASTVisitor.java#L1352

But the same problem happens for namespaces. In my opinion, the problem why comments are missed in native AST comes from the fact that we can't find associated object in comments map.
If you take a look into _debug_ snapshot you'll see that in `commentMap` we keep the `gui` object's *parent* (not the current object). In other words, we don't add `gui namespace` leading comments, because we can't find a right key object in `commentMap`
<img width="690" alt="Screen Shot 2019-08-27 at 23 09 12" src="https://user-images.githubusercontent.com/4056521/63809009-8ab91580-c921-11e9-8d85-537407bb5b01.png">

**Comment by kuba--** [comment]
I mark it as blocked because of two reasons:
- `namespace` comments are missed
- based on discussion with @dennwc:
> And since C++ driver doesn't yet have machinery to move comments around, we should drop the field for now, as done for other node types in this driver. Later we can come back and fix it properly.
